### PR TITLE
refactor: make openvr a feature

### PR DESCRIPTION
**Pull request by technobaboo**
it won't compile on some systems and some people don't need it, why not make it a feature?

### CODE REVIEW

**Comment by yshui** [comment]
Thanks! maybe we can make openxr a feature too?

**Review by yshui — APPROVED** [review]
LGTM

**Comment by technobaboo** [comment]
should i make it a feature before we merge the branch?

**Comment by yshui** [comment]
@technobaboo yeah, if you can do that that'll be great

**Comment by technobaboo** [comment]
okay but idk how to make it work properly if you don't select either feature, or what to make default

**Comment by technobaboo** [comment]
ok you'll need to test openvr-only mode as i can't build openvr on my system lol so that's why i made the patch

**Comment by yshui** [comment]
Looks reasonably reasonable. If something breaks I can fix that later myself.

**Pull request merged**
